version: "3"
services:
  app:
    container_name: examen-cote-serveur-sp-2223
    restart: always
    build: .
    ports:
      - '9090:8090'
    links:
      - mongo
  mongo:
    container_name: examen-mongo
    image: mongo:5
    ports:
      - "27017:8091"
    volumes:
      - ./data/db:/data/db

